mongo-up:
	docker compose -f fhooe-mongo-dock/docker-compose.yml up -d

mongo-down:
	docker compose -f fhooe-mongo-dock/docker-compose.yml down

mongo:
	docker exec -it mongodb /bin/bash -c "mongosh"

